### ISSUE TITLE
近日随笔

### ISSUE THREAD

**Issue by hiyouga** [hiyouga/hiyouga-blog-project#33]
明明只是过了四五天，却感觉已经好久没有看过这里了…随着开学后的日子一天天变忙，写博客的空闲时间也会越来越少，今后估计都只能月更了 233 博客也有一些重要的功能还没有添加，只能抽空做一下下了。（从开坑到跑路
回首过去一个月，寒假时光在不知不觉中流走，当时也列过寒假 plan 的，结果做了个 p，因为太 lan。虽说计划没有很好地完成，不过也是有一定收获吧，学习到不少新知识，至少没有去年暑假过得那么咸鱼，现在说再多也没什么用，已经是过去时的东西了。
如今已经来到了自己大学生活的第二个学期，同时也是对以后的三年极其重要的一个学期。开学一周以来，调整了一下自己的作息，目前看起来收效良好，今后也要一直这样坚持下去，其实这样子也蛮好的，甚至都搞不清自己当初为什么要修仙了。这学期课依旧很多，压力蛮大的，但是相信自己可以很好地度过这关键的半年，除了顺利结课以外还要尽可能地取得好些的分数，以挽救我那可怜的 GPA。上学期几乎天天修仙，不但对身体不好，学习效率也很低，最后直接造成了 GPA 跌破 3.0 的惨剧…好吧，丢人现场，估计来自学院的一张学业预警书也是逃不掉喽。成绩问题毕竟事关半年后的选专业，还是不得不加把劲了，兴趣爱好之类的暂时放下，那些毫无意义的事情更是要坚决抛弃，时间是很宝贵的，珍惜自己还可以继续努力的半年，不管最后结果如何，但是如一句话所说：什么时候开始努力都不算晚。今天听完学科前沿讲座，更是意识到自己身上的压迫感，一定要承受下来，并且化为自己前进的动力。不知四个月后的今天，自己还能不能像当初高考一样，笑着走下去。
啊啊，咱只是个渣文笔的理科生，怎么写都不能很好地表达内心的想法，更别说比得上那些大佬们的博客了，如果觉得无聊透顶，就当作是我自言自语吧。

> 未来でも過去でもない 自分が前を向いている
> 変わらない想いのままで
> Till I can see you again
> ——榊原ゆい《Till I can see you again》

<audio src="http://www.hiyouga.top/html/netease/bbsapi/api.php?id=412178476" controls=""></audio>
（音乐只能在博客页面听，GitHub貌似会屏蔽掉）

**Comment by Iriasu** [comment]
为冰河姐姐加油qaq

**Comment by hiyouga** [comment]
@Iriasu 
谢谢小姐姐>ω<

**Comment by Myriad-Dreamin** [comment]
加油，我下星期也参加校队选拔了..

**Comment by hiyouga** [comment]
@Myriad-Dreamin 
抱紧未来ACM大佬的大腿
